#!/usr/bin/env python3
"""Generates assets/data/prepositions.json for PrepWise."""
import json, os

OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "data", "prepositions.json")

def c(id, cid, sent, cor, dist, rule, diff, famous=False, irr=False, src=None):
    return {"id": id, "cluster_id": cid, "sentence": sent, "correct": cor,
            "distractors": dist, "rule_id": rule, "tags": ["difficulty_" + str(diff)],
            "is_famous": famous, "is_irregular": irr, "source": src}

def cc(id, sent, cor, dist, diff, tag):
    return {"id": id, "cluster_id": "collocations", "sentence": sent, "correct": cor,
            "distractors": dist, "rule_id": "rule_irregular_collocation",
            "tags": ["difficulty_" + str(diff), tag], "is_famous": False,
            "is_irregular": True, "source": None}

P="place_in_on_at"; T="time_in_on_at"; D="duration_by_until_for"
M="movement_to_for_with"; O="origin_of_about_from"
RI="rule_in_enclosed_space"; RA="rule_in_area"; RS="rule_on_surface"
RT="rule_on_transport"; RP="rule_at_specific_point"; RE="rule_at_event"
RL="rule_in_long_period"; RD="rule_on_day"; RAt="rule_at_time"
RBy="rule_by_deadline"; RU="rule_until_continuous"; RF="rule_for_duration"
RTo="rule_to_destination"; RFp="rule_for_purpose"; RW="rule_with_accompaniment"
RFr="rule_from_origin"; ROf="rule_of_possession"; RAb="rule_about_topic"

RULES = {
  "rule_in_enclosed_space": {"id":"rule_in_enclosed_space","short":"IN — enclosed spaces, rooms, buildings, containers","example":"in the room, in a box, in the car, in a hotel"},
  "rule_in_area": {"id":"rule_in_area","short":"IN — countries, cities, regions, large open areas","example":"in France, in London, in the north, in the park"},
  "rule_on_surface": {"id":"rule_on_surface","short":"ON — surfaces (horizontal or vertical), things seen as flat","example":"on the table, on the floor, on the wall, on the ceiling"},
  "rule_on_transport": {"id":"rule_on_transport","short":"ON — public transport and large vehicles","example":"on the bus, on a train, on a plane, on a ship"},
  "rule_at_specific_point": {"id":"rule_at_specific_point","short":"AT — specific points, addresses, precise locations","example":"at the station, at home, at the top, at the door"},
  "rule_at_event": {"id":"rule_at_event","short":"AT — events, institutions, gatherings","example":"at the party, at school, at work, at a concert"},
  "rule_in_long_period": {"id":"rule_in_long_period","short":"IN — months, years, centuries, seasons, parts of the day","example":"in January, in 2023, in the morning, in summer"},
  "rule_on_day": {"id":"rule_on_day","short":"ON — days of the week, specific dates, named days","example":"on Monday, on the 5th, on my birthday, on New Year's Day"},
  "rule_at_time": {"id":"rule_at_time","short":"AT — clock times and fixed time points","example":"at 5pm, at noon, at midnight, at dawn"},
  "rule_by_deadline": {"id":"rule_by_deadline","short":"BY — no later than a certain point (deadline)","example":"by Friday, by noon, by the end of the week"},
  "rule_until_continuous": {"id":"rule_until_continuous","short":"UNTIL/TILL — continuously up to a point in time","example":"until midnight, till Monday, until she arrives"},
  "rule_for_duration": {"id":"rule_for_duration","short":"FOR — over a period of time (how long)","example":"for two hours, for years, for a long time, for a week"},
  "rule_to_destination": {"id":"rule_to_destination","short":"TO — movement toward a destination","example":"go to school, travel to France, drive to work"},
  "rule_for_purpose": {"id":"rule_for_purpose","short":"FOR — purpose, benefit, or intended recipient","example":"for you, work for a company, for fun, a gift for her"},
  "rule_with_accompaniment": {"id":"rule_with_accompaniment","short":"WITH — accompaniment, using a tool or ingredient","example":"with friends, with a knife, pay with cash, coffee with milk"},
  "rule_from_origin": {"id":"rule_from_origin","short":"FROM — starting point, origin, or source","example":"from London, from the beginning, a letter from her"},
  "rule_of_possession": {"id":"rule_of_possession","short":"OF — belonging, content, or part of a whole","example":"the top of the hill, a cup of tea, a friend of mine"},
  "rule_about_topic": {"id":"rule_about_topic","short":"ABOUT — concerning a topic or subject","example":"talk about work, worried about money, a book about history"},
  "rule_irregular_collocation": {"id":"rule_irregular_collocation","short":"Fixed phrase — this preposition does not follow spatial logic. It must be memorized.","example":"good AT, interested IN, depend ON, responsible FOR"},
}

place_cards = [
  c("p_001",P,"She arrived ___ the airport just before midnight.","at",["in","on","to"],RP,1),
  c("p_002",P,"The book is ___ the shelf above the desk.","on",["in","at","under"],RS,1),
  c("p_003",P,"He grew up ___ a small village in the south.","in",["on","at","from"],RA,1),
  c("p_004",P,"We met ___ the corner of Park Street.","at",["in","on","by"],RP,1),
  c("p_005",P,"There's a strange stain ___ the ceiling.","on",["in","at","across"],RS,1),
  c("p_006",P,"She has lived ___ Japan for three years.","in",["on","at","to"],RA,1),
  c("p_007",P,"The children are playing ___ the garden.","in",["on","at","through"],RA,1),
  c("p_008",P,"He left his keys ___ the kitchen counter.","on",["in","at","by"],RS,1),
  c("p_009",P,"I'll wait for you ___ the entrance.","at",["in","on","by"],RP,1),
  c("p_010",P,"She works ___ the third floor of the building.","on",["in","at","to"],RS,2),
  c("p_011",P,"We had a wonderful dinner ___ a restaurant by the river.","at",["in","on","to"],RE,2),
  c("p_012",P,"He fell asleep ___ the bus on the way home.","on",["in","at","during"],RT,2),
  c("p_013",P,"She found her phone ___ her coat pocket.","in",["on","at","inside"],RI,1),
  c("p_014",P,"They sat ___ the front row during the show.","in",["on","at","to"],RI,1),
  c("p_015",P,"He hung a painting ___ the wall beside the window.","on",["in","at","above"],RS,1),
  c("p_016",P,"She was waiting ___ the bus stop when it started to rain.","at",["in","on","by"],RP,1),
  c("p_017",P,"The cat is sleeping ___ the sofa.","on",["in","at","under"],RS,1),
  c("p_018",P,"We arrived ___ the train station an hour early.","at",["in","on","to"],RP,1),
  c("p_019",P,"There was a spider ___ the corner of the room.","in",["on","at","by"],RI,2),
  c("p_020",P,"He works ___ a hospital in the city centre.","at",["in","on","for"],RE,2),
  c("p_021",P,"The children were splashing around ___ the pool.","in",["on","at","through"],RI,1),
  c("p_022",P,"I saw her name ___ the list on the noticeboard.","on",["in","at","from"],RS,1),
  c("p_023",P,"We all gathered ___ the town square for the celebrations.","in",["on","at","to"],RA,1),
  c("p_024",P,"She is studying ___ a university in Edinburgh.","at",["in","on","for"],RE,2),
  c("p_025",P,"He put the glasses ___ the bathroom cabinet.","in",["on","at","inside"],RI,1),
  c("p_026",P,"The dog was sitting ___ the doorstep.","on",["in","at","by"],RS,1),
  c("p_027",P,"They met ___ a conference in Berlin.","at",["in","on","during"],RE,2),
  c("p_028",P,"She grew up ___ the north of England.","in",["on","at","from"],RA,1),
  c("p_029",P,"There are beautiful murals painted ___ the ceiling of the chapel.","on",["in","at","across"],RS,2),
  c("p_030",P,"He sat ___ the top of the hill and watched the sunset.","on",["in","at","by"],RS,1),
  c("p_031",P,"We stayed ___ a bed and breakfast near the coast.","at",["in","on","for"],RP,2),
  c("p_032",P,"She left a note ___ his desk before leaving.","on",["in","at","by"],RS,1),
  c("p_033",P,"They live ___ a quiet suburb outside the city.","in",["on","at","by"],RA,1),
  c("p_034",P,"He was sitting ___ the back of the room, away from the screen.","at",["in","on","to"],RP,2),
  c("p_035",P,"She put her bag ___ the overhead compartment.","in",["on","at","into"],RI,2),
  c("p_036",P,"The poster was stuck ___ the door of his room.","on",["in","at","to"],RS,1),
  c("p_037",P,"He was born ___ a small coastal town.","in",["on","at","from"],RA,1),
  c("p_038",P,"She was ___ the kitchen when the phone rang.","in",["on","at","into"],RI,1),
  c("p_039",P,"They met ___ the wedding reception last summer.","at",["in","on","during"],RE,2),
  c("p_040",P,"She noticed a crack ___ the ceiling above the bed.","in",["on","at","through"],RI,2),
  c("p_041",P,"He was standing ___ the window, looking out at the street.","at",["in","on","by"],RP,2),
  c("p_042",P,"She spent the summer ___ her grandmother's house in the countryside.","at",["in","on","to"],RP,2),
  c("p_043",P,"They were ___ the plane for over ten hours.","on",["in","at","during"],RT,2),
  c("p_044",P,"I found a coin ___ the pavement near the market.","on",["in","at","from"],RS,1),
  c("p_045",P,"He is currently ___ a conference abroad.","at",["in","on","for"],RE,2),
  c("p_046",P,"She put the flowers ___ a vase on the windowsill.","in",["on","at","into"],RI,1),
  c("p_047",P,"They got stuck ___ the lift for nearly an hour.","in",["on","at","inside"],RI,2),
  c("p_048",P,"She sat ___ the front of the car because she gets carsick.","in",["on","at","to"],RI,2),
  c("p_049",P,"He was leaning ___ the railing at the top of the stairs.","on",["in","at","against"],RS,2),
  c("p_050",P,"The keys are ___ the hook by the front door.","on",["in","at","near"],RS,1),
  c("p_051",P,"She was ___ the dentist when I tried to call her.","at",["in","on","to"],RP,2),
  c("p_052",P,"He lives ___ a farm just outside the village.","on",["in","at","by"],RS,3),
  c("p_053",P,"The nearest supermarket is ___ the end of the road.","at",["in","on","by"],RP,2),
  c("p_054",P,"She noticed her name ___ the screen.","on",["in","at","from"],RS,1),
  c("p_055",P,"He was ___ the top of his class at medical school.","at",["in","on","from"],RP,3),
  c("p_056",P,"There was a small cafe ___ the ground floor of the hotel.","on",["in","at","by"],RS,2),
  c("p_057",P,"She was born ___ a hospital in Geneva.","in",["on","at","from"],RI,2),
  c("p_058",P,"The hotel is ___ the corner of Fifth Avenue.","on",["in","at","by"],RS,3),
  c("p_059",P,"There's a beautiful painting ___ the wall of the dining room.","on",["in","at","above"],RS,1),
  c("p_060",P,"She spotted him ___ the far side of the room.","on",["in","at","to"],RS,2),
]

time_cards = [
  c("t_001",T,"The meeting starts ___ 9 o'clock sharp.","at",["in","on","by"],RAt,1),
  c("t_002",T,"She was born ___ a cold December morning.","on",["in","at","during"],RD,2),
  c("t_003",T,"We usually go skiing ___ winter.","in",["on","at","during"],RL,1),
  c("t_004",T,"The store opens ___ 8 in the morning.","at",["in","on","from"],RAt,1),
  c("t_005",T,"He started his new job ___ Monday.","on",["in","at","from"],RD,1),
  c("t_006",T,"They got married ___ June 1998.","in",["on","at","during"],RL,1),
  c("t_007",T,"I always feel tired ___ the afternoon.","in",["on","at","during"],RL,1),
  c("t_008",T,"The ceremony will be held ___ the 15th of August.","on",["in","at","by"],RD,1),
  c("t_009",T,"Everything goes quiet ___ midnight.","at",["in","on","by"],RAt,1),
  c("t_010",T,"She called me ___ my birthday.","on",["in","at","for"],RD,2),
  c("t_011",T,"She usually calls her parents ___ Sunday evenings.","on",["in","at","during"],RD,1),
  c("t_012",T,"The results will be announced ___ the end of the week.","at",["in","on","by"],RAt,2),
  c("t_013",T,"He wrote his first novel ___ his twenties.","in",["on","at","during"],RL,2),
  c("t_014",T,"She always has breakfast ___ seven o'clock.","at",["in","on","by"],RAt,1),
  c("t_015",T,"We left the city ___ a rainy Tuesday afternoon.","on",["in","at","during"],RD,2),
  c("t_016",T,"There were no computers ___ the nineteenth century.","in",["on","at","during"],RL,2),
  c("t_017",T,"The library opens ___ 9 am and closes at 8 pm.","at",["in","on","from"],RAt,1),
  c("t_018",T,"They celebrated ___ New Year's Eve with a big dinner.","on",["in","at","during"],RD,2),
  c("t_019",T,"Flowers bloom ___ spring in this part of the country.","in",["on","at","during"],RL,1),
  c("t_020",T,"She arrived ___ exactly half past three.","at",["in","on","by"],RAt,1),
  c("t_021",T,"They announced the winner ___ Christmas Day.","on",["in","at","during"],RD,1),
  c("t_022",T,"He was born ___ 1985, just before the internet became widespread.","in",["on","at","during"],RL,1),
  c("t_023",T,"The train departs ___ quarter past six.","at",["in","on","by"],RAt,1),
  c("t_024",T,"She visits her parents ___ Easter every year.","at",["in","on","during"],RAt,3),
  c("t_025",T,"He doesn't like to eat too much ___ the evening.","in",["on","at","during"],RL,1),
  c("t_026",T,"The shop closes early ___ Saturdays.","on",["in","at","during"],RD,1),
  c("t_027",T,"She learnt to drive ___ 2019.","in",["on","at","during"],RL,1),
  c("t_028",T,"They usually have a team lunch ___ Fridays.","on",["in","at","by"],RD,1),
  c("t_029",T,"I prefer working ___ the morning when everything is quiet.","in",["on","at","during"],RL,1),
  c("t_030",T,"She rang the doorbell ___ exactly midnight.","at",["in","on","by"],RAt,1),
  c("t_031",T,"He was promoted ___ the first of September.","on",["in","at","by"],RD,1),
  c("t_032",T,"I'll call you back ___ lunchtime.","at",["in","on","during"],RAt,2),
  c("t_033",T,"She always feels restless ___ autumn.","in",["on","at","during"],RL,1),
  c("t_034",T,"She always sleeps late ___ weekends.","on",["in","at","during"],RD,1),
  c("t_035",T,"The concert begins ___ 8 o'clock sharp.","at",["in","on","from"],RAt,1),
  c("t_036",T,"A lot has changed ___ the past decade.","in",["on","at","during"],RL,2),
  c("t_037",T,"He proposed to her ___ Valentine's Day.","on",["in","at","during"],RD,1),
  c("t_038",T,"Strange things seem to happen ___ night in this town.","at",["in","on","during"],RAt,2),
  c("t_039",T,"She finished her PhD ___ her early thirties.","in",["on","at","during"],RL,2),
  c("t_040",T,"He discovered his passion for cooking ___ his first year at university.","in",["on","at","during"],RL,2),
  c("t_041",T,"The fire alarm went off ___ the early hours of the morning.","in",["on","at","during"],RL,2),
  c("t_042",T,"They signed the contract ___ 14 March.","on",["in","at","by"],RD,1),
  c("t_043",T,"She usually studies ___ night, when the house is quiet.","at",["in","on","during"],RAt,2),
  c("t_044",T,"The stadium was built ___ the 1960s.","in",["on","at","during"],RL,1),
  c("t_045",T,"She checks her email first thing ___ the morning.","in",["on","at","during"],RL,1),
  c("t_046",T,"She was offered the job ___ the very last day of the month.","on",["in","at","by"],RD,2),
  c("t_047",T,"They moved to the new house ___ August.","in",["on","at","during"],RL,1),
  c("t_048",T,"He arrived home ___ dusk, just as the lights came on.","at",["in","on","by"],RAt,2),
  c("t_049",T,"The market takes place ___ the first Sunday of each month.","on",["in","at","by"],RD,2),
  c("t_050",T,"She hopes to retire ___ her mid-sixties.","in",["on","at","by"],RL,2),
]

duration_cards = [
  c("d_001",D,"Please submit your report ___ Friday.","by",["until","for","on"],RBy,1),
  c("d_002",D,"She studied ___ three hours without a break.","for",["by","until","during"],RF,1),
  c("d_003",D,"We waited at the station ___ the last train arrived.","until",["by","for","when"],RU,1),
  c("d_004",D,"I need this done ___ noon at the latest.","by",["until","for","at"],RBy,1),
  c("d_005",D,"They have been friends ___ over twenty years.","for",["by","until","since"],RF,2),
  c("d_006",D,"He kept working ___ he couldn't keep his eyes open.","until",["by","for","while"],RU,2),
  c("d_007",D,"Can you finish the painting ___ the end of the month?","by",["until","for","at"],RBy,2),
  c("d_008",D,"The museum stays open ___ 9 o'clock in the evening.","until",["by","for","at"],RU,1),
  c("d_009",D,"The builders worked ___ six months to complete the extension.","for",["by","until","during"],RF,1),
  c("d_010",D,"You must return the library book ___ next Thursday.","by",["until","for","on"],RBy,1),
  c("d_011",D,"They danced ___ the early hours of the morning.","until",["by","for","through"],RU,2),
  c("d_012",D,"She has been living abroad ___ the past five years.","for",["by","until","during"],RF,2),
  c("d_013",D,"He needs to call the client ___ 3 pm.","by",["until","for","at"],RBy,1),
  c("d_014",D,"She kept all of his letters ___ the day she died.","until",["by","for","to"],RU,2),
  c("d_015",D,"They were stuck in traffic ___ two hours.","for",["by","until","during"],RF,1),
  c("d_016",D,"Can you wait ___ I get back?","until",["by","for","to"],RU,1),
  c("d_017",D,"He saved up ___ months before he could buy the car.","for",["by","until","during"],RF,2),
  c("d_018",D,"The proposal must be submitted ___ end of business today.","by",["until","for","at"],RBy,2),
  c("d_019",D,"He stayed ___ everyone else had left the party.","until",["by","for","while"],RU,2),
  c("d_020",D,"She has been working at the same company ___ thirty years.","for",["by","until","since"],RF,2),
  c("d_021",D,"We need to leave ___ midday to catch the ferry.","by",["until","for","at"],RBy,2),
  c("d_022",D,"The shop is open ___ 10 pm every day.","until",["by","for","to"],RU,1),
  c("d_023",D,"She slept ___ fourteen hours after the surgery.","for",["by","until","during"],RF,1),
  c("d_024",D,"I'll have the report ready ___ the morning.","by",["until","for","in"],RBy,2),
  c("d_025",D,"He held onto the rope ___ his arms gave out.","until",["by","for","while"],RU,2),
  c("d_026",D,"She worked overtime ___ weeks to finish the project.","for",["by","until","during"],RF,1),
  c("d_027",D,"Could you hold the line ___ she is available?","until",["by","for","while"],RU,2),
  c("d_028",D,"The application deadline is ___ the 30th of June.","by",["until","for","on"],RBy,2),
  c("d_029",D,"They waited ___ the storm passed before setting off.","until",["by","for","while"],RU,1),
  c("d_030",D,"She's been on the phone ___ an hour.","for",["by","until","since"],RF,1),
  c("d_031",D,"All invoices must be paid ___ the end of the quarter.","by",["until","for","at"],RBy,2),
  c("d_032",D,"He practised guitar every day ___ he could play the full song.","until",["by","for","while"],RU,2),
  c("d_033",D,"I'll keep the table reserved ___ 8 pm, but after that it's gone.","until",["by","for","to"],RU,3),
  c("d_034",D,"The food bank has been running ___ over a decade.","for",["by","until","during"],RF,2),
  c("d_035",D,"Make sure the contract is signed ___ close of play Friday.","by",["until","for","at"],RBy,3),
  c("d_036",D,"She played the piano ___ she forgot all about the time.","until",["by","for","while"],RU,2),
  c("d_037",D,"He waited ___ the very last moment to buy his train ticket.","until",["by","for","to"],RU,3),
  c("d_038",D,"He had been on the waiting list ___ almost two years.","for",["by","until","during"],RF,2),
  c("d_039",D,"The band played non-stop ___ midnight.","until",["by","for","to"],RU,2),
  c("d_040",D,"She needs to complete the online course ___ the end of the month or lose access.","by",["until","for","at"],RBy,3),
]

movement_cards = [
  c("m_001",M,"She walked ___ the library after school.","to",["for","with","into"],RTo,1),
  c("m_002",M,"He bought flowers ___ his mother.","for",["to","with","of"],RFp,1),
  c("m_003",M,"She cut the bread ___ a sharp knife.","with",["to","for","by"],RW,1),
  c("m_004",M,"They are travelling ___ Rome next week.","to",["for","with","in"],RTo,1),
  c("m_005",M,"This sandwich is ___ you — I made it specially.","for",["to","with","of"],RFp,1),
  c("m_006",M,"He came home ___ two bags of groceries.","with",["to","for","and"],RW,1),
  c("m_007",M,"She sent a long email ___ her manager.","to",["for","with","at"],RTo,2),
  c("m_008",M,"He goes jogging ___ his dog every morning.","with",["to","for","and"],RW,1),
  c("m_009",M,"She mixed the flour ___ butter and sugar.","with",["to","for","and"],RW,1),
  c("m_010",M,"He drove her ___ the hospital immediately.","to",["for","with","at"],RTo,1),
  c("m_011",M,"She brought a bottle of wine ___ the party.","to",["for","with","at"],RTo,2),
  c("m_012",M,"They rented a cottage ___ a week by the sea.","for",["to","with","on"],RFp,2),
  c("m_013",M,"He paid ___ the drinks in cash.","for",["to","with","of"],RFp,1),
  c("m_014",M,"She signed the document ___ a pen she borrowed from the receptionist.","with",["to","for","by"],RW,1),
  c("m_015",M,"The coach spoke ___ the team before the match.","to",["for","with","at"],RTo,1),
  c("m_016",M,"She is looking ___ a new flat closer to work.","for",["to","with","at"],RFp,1),
  c("m_017",M,"He arrived at the event ___ his whole family in tow.","with",["to","for","and"],RW,2),
  c("m_018",M,"They donated the money ___ a local food bank.","to",["for","with","at"],RTo,2),
  c("m_019",M,"She is saving up ___ a trip to South America.","for",["to","with","on"],RFp,1),
  c("m_020",M,"He sent a postcard ___ his friends back home.","to",["for","with","at"],RTo,1),
  c("m_021",M,"She cooked the pasta ___ olive oil and garlic.","with",["to","for","in"],RW,1),
  c("m_022",M,"We're going ___ the cinema tonight — do you want to come?","to",["for","with","at"],RTo,1),
  c("m_023",M,"He did it ___ fun, not because anyone asked him to.","for",["to","with","of"],RFp,1),
  c("m_024",M,"The room was decorated ___ balloons and streamers.","with",["to","for","by"],RW,1),
  c("m_025",M,"She applied ___ a scholarship to study overseas.","for",["to","with","at"],RFp,2),
  c("m_026",M,"He flew ___ New York on business last spring.","to",["for","with","in"],RTo,1),
  c("m_027",M,"She wrote the letter ___ a fountain pen.","with",["to","for","by"],RW,1),
  c("m_028",M,"She offered her seat ___ an elderly passenger.","to",["for","with","at"],RTo,2),
  c("m_029",M,"They charged me extra ___ the checked baggage.","for",["to","with","on"],RFp,2),
  c("m_030",M,"He sprinkled the salad ___ a little salt and pepper.","with",["to","for","by"],RW,1),
  c("m_031",M,"She ran ___ the door when the bell rang.","to",["for","with","at"],RTo,1),
  c("m_032",M,"They gathered there ___ a specific purpose, though no one said what.","for",["to","with","at"],RFp,2),
  c("m_033",M,"He filled the bath ___ warm water and a few drops of lavender oil.","with",["to","for","by"],RW,1),
  c("m_034",M,"She returned the book ___ the library on time.","to",["for","with","at"],RTo,1),
  c("m_035",M,"They sell fresh bread here ___ only one pound a loaf.","for",["to","with","at"],RFp,2),
  c("m_036",M,"He cleaned the windows ___ a damp cloth.","with",["to","for","by"],RW,1),
  c("m_037",M,"She handed the report ___ her supervisor before the deadline.","to",["for","with","at"],RTo,1),
  c("m_038",M,"They are looking ___ someone to lead the project.","for",["to","with","at"],RFp,1),
  c("m_039",M,"He finished the puzzle ___ help from his daughter.","with",["to","for","by"],RW,2),
  c("m_040",M,"She went ___ the doctor after three days of not feeling well.","to",["for","with","at"],RTo,1),
]

origin_cards = [
  c("o_001",O,"She received a letter ___ her old friend in Canada.","from",["of","about","by"],RFr,1),
  c("o_002",O,"He told me everything ___ his trip to Morocco.","about",["from","of","on"],RAb,1),
  c("o_003",O,"This is a picture ___ my grandmother as a young woman.","of",["from","about","with"],ROf,1),
  c("o_004",O,"Where are you originally ___?","from",["of","about","at"],RFr,1),
  c("o_005",O,"They argued ___ money for hours.","about",["from","of","on"],RAb,1),
  c("o_006",O,"The roof ___ the old house was leaking badly.","of",["from","about","in"],ROf,1),
  c("o_007",O,"She comes ___ a long line of musicians.","from",["of","about","in"],RFr,2),
  c("o_008",O,"The documentary is ___ the lives of deep-sea fishermen.","about",["from","of","on"],RAb,1),
  c("o_009",O,"She got a scholarship ___ the best university in the country.","from",["of","about","at"],RFr,2),
  c("o_010",O,"The smell ___ fresh bread filled the whole street.","of",["from","about","with"],ROf,1),
  c("o_011",O,"He complained ___ the noise coming from upstairs.","about",["from","of","on"],RAb,1),
  c("o_012",O,"This tea comes all the way ___ a small region in Sri Lanka.","from",["of","about","in"],RFr,1),
  c("o_013",O,"The bottom ___ the sea is full of life we haven't discovered yet.","of",["from","about","in"],ROf,1),
  c("o_014",O,"She knows everything ___ the history of that region.","about",["from","of","on"],RAb,1),
  c("o_015",O,"He recovered quickly ___ his illness.","from",["of","about","after"],RFr,2),
  c("o_016",O,"The title ___ the film comes from a famous poem.","of",["from","about","in"],ROf,2),
  c("o_017",O,"They talked ___ their plans for the summer for hours.","about",["from","of","on"],RAb,1),
  c("o_018",O,"She learned to cook ___ her grandmother.","from",["of","about","with"],RFr,2),
  c("o_019",O,"The price ___ the ticket includes all taxes and fees.","of",["from","about","for"],ROf,1),
  c("o_020",O,"They were curious ___ the strange light in the sky.","about",["from","of","in"],RAb,1),
  c("o_021",O,"He was exhausted ___ the long journey.","from",["of","about","after"],RFr,2),
  c("o_022",O,"A large part ___ the city was damaged in the flood.","of",["from","about","in"],ROf,1),
  c("o_023",O,"She knows a lot ___ traditional Japanese architecture.","about",["from","of","on"],RAb,1),
  c("o_024",O,"The flavour ___ this dish comes from a blend of spices.","of",["from","about","in"],ROf,1),
  c("o_025",O,"He has been living far ___ his family for many years.","from",["of","about","away"],RFr,2),
  c("o_026",O,"She published an article ___ the effects of social media on teenagers.","about",["from","of","on"],RAb,2),
  c("o_027",O,"The news ___ the discovery surprised the entire scientific community.","of",["from","about","on"],ROf,2),
  c("o_028",O,"He translated the text directly ___ the original Latin.","from",["of","about","in"],RFr,2),
  c("o_029",O,"She was reading a book ___ the life of Marie Curie.","about",["from","of","on"],RAb,1),
  c("o_030",O,"The value ___ the painting has increased dramatically over the years.","of",["from","about","for"],ROf,1),
  c("o_031",O,"The wool in this jumper comes ___ alpacas raised in Peru.","from",["of","about","in"],RFr,2),
  c("o_032",O,"She's always talking ___ her plans to move abroad.","about",["from","of","on"],RAb,1),
  c("o_033",O,"A third ___ the profits went to local charities.","of",["from","about","in"],ROf,1),
  c("o_034",O,"He graduated ___ a top engineering school last year.","from",["of","about","at"],RFr,1),
  c("o_035",O,"She's been writing a column ___ the challenges facing new parents.","about",["from","of","on"],RAb,2),
  c("o_036",O,"The end ___ the story was completely unexpected.","of",["from","about","in"],ROf,1),
  c("o_037",O,"She heard the news ___ a colleague she bumped into at the supermarket.","from",["of","about","by"],RFr,2),
  c("o_038",O,"He's been warned ___ the risks several times.","about",["from","of","on"],RAb,1),
  c("o_039",O,"The handle ___ the door was loose and kept turning without opening it.","of",["from","about","on"],ROf,1),
  c("o_040",O,"She borrowed the recipe ___ an old book she found in the attic.","from",["of","about","in"],RFr,2),
]

collocation_cards = [
  cc("c_001","He has always been very good ___ languages.","at",["in","with","for"],2,"adjective_prep"),
  cc("c_002","She is really interested ___ marine biology.","in",["at","about","for"],1,"adjective_prep"),
  cc("c_003","Everything depends ___ the weather tomorrow.","on",["in","at","from"],2,"verb_prep"),
  cc("c_004","She feels very proud ___ her daughter's achievement.","of",["for","about","in"],1,"adjective_prep"),
  cc("c_005","He is responsible ___ the entire project.","for",["of","about","with"],2,"adjective_prep"),
  cc("c_006","They listened carefully ___ the instructions.","to",["at","for","with"],1,"verb_prep"),
  cc("c_007","She agreed ___ everything he said.","with",["to","on","about"],2,"verb_prep"),
  cc("c_008","He is married ___ a doctor he met in university.","to",["with","by","for"],2,"adjective_prep"),
  cc("c_009","She is afraid ___ flying, so she takes the train.","of",["about","from","with"],1,"adjective_prep"),
  cc("c_010","They applied ___ a grant to fund their research.","for",["to","at","about"],2,"verb_prep"),
  cc("c_011","She is always tired ___ doing the same routine every day.","of",["from","with","about"],1,"adjective_prep"),
  cc("c_012","The bottle is full ___ sand from the beach.","of",["with","from","in"],1,"adjective_prep"),
  cc("c_013","This design is very similar ___ the one they used last year.","to",["as","with","from"],2,"adjective_prep"),
  cc("c_014","Her approach is quite different ___ what I expected.","from",["to","than","with"],2,"adjective_prep"),
  cc("c_015","She is grateful ___ all the support she received.","for",["to","about","of"],1,"adjective_prep"),
  cc("c_016","The region is famous ___ its olive oil and wine.","for",["of","about","by"],1,"adjective_prep"),
  cc("c_017","He was angry ___ his colleague for not telling him sooner.","with",["at","about","to"],3,"adjective_prep"),
  cc("c_018","She is worried ___ the results of the exam.","about",["for","of","from"],1,"adjective_prep"),
  cc("c_019","He finds it hard to concentrate ___ one thing for too long.","on",["in","at","about"],1,"verb_prep"),
  cc("c_020","We can always rely ___ her to get the job done.","on",["in","upon","at"],2,"verb_prep"),
  cc("c_021","The team consists ___ five members from different departments.","of",["from","in","with"],1,"verb_prep"),
  cc("c_022","This ring belonged ___ my great-grandmother.","to",["of","with","from"],1,"verb_prep"),
  cc("c_023","He was accused ___ stealing from the company.","of",["for","about","with"],2,"verb_prep"),
  cc("c_024","She dreams ___ owning her own restaurant one day.","of",["for","in","on"],2,"verb_prep"),
  cc("c_025","She's been waiting ___ a reply for over two weeks.","for",["to","on","about"],1,"verb_prep"),
  cc("c_026","He just sat there and stared ___ the screen without moving.","at",["to","on","in"],1,"verb_prep"),
  cc("c_027","Did you remember to pay ___ the parking?","for",["to","about","on"],1,"verb_prep"),
  cc("c_028","Can you compare these two results ___ the figures from last year?","with",["to","against","from"],3,"verb_prep"),
  cc("c_029","She has suffered ___ migraines since she was a teenager.","from",["with","of","at"],1,"verb_prep"),
  cc("c_030","The argument resulted ___ both of them refusing to speak to each other.","in",["from","of","with"],2,"verb_prep"),
  cc("c_031","She doesn't believe ___ making promises she can't keep.","in",["on","at","with"],2,"verb_prep"),
  cc("c_032","He insisted ___ paying for everyone's dinner.","on",["in","at","for"],2,"verb_prep"),
  cc("c_033","She eventually succeeded ___ convincing the board to approve the plan.","in",["at","with","on"],2,"verb_prep"),
  cc("c_034","He has always specialised ___ tax law.","in",["at","on","with"],1,"verb_prep"),
  cc("c_035","She is very keen ___ learning new skills.","on",["in","for","about"],2,"adjective_prep"),
  cc("c_036","He is not very good ___ remembering names.","at",["in","with","on"],1,"adjective_prep"),
  cc("c_037","She felt ashamed ___ what she had done.","of",["about","for","from"],2,"adjective_prep"),
  cc("c_038","He is very fond ___ classical music.","of",["in","about","with"],1,"adjective_prep"),
  cc("c_039","She is capable ___ much more than she lets on.","of",["in","at","for"],2,"adjective_prep"),
  cc("c_040","He is passionate ___ environmental issues.","about",["for","in","of"],1,"adjective_prep"),
  cc("c_041","She's been complaining ___ her back for months.","about",["of","from","on"],1,"verb_prep"),
  cc("c_042","He has to deal ___ a lot of complaints from customers.","with",["in","for","about"],2,"verb_prep"),
  cc("c_043","She is very sensitive ___ criticism.","to",["about","of","with"],2,"adjective_prep"),
  cc("c_044","He is aware ___ the risks involved.","of",["about","with","from"],1,"adjective_prep"),
  cc("c_045","They had to apologise ___ being late to the meeting.","for",["about","to","of"],1,"verb_prep"),
  cc("c_046","She is addicted ___ coffee and can't function without it.","to",["on","in","with"],1,"adjective_prep"),
  cc("c_047","He takes great pride ___ his work.","in",["of","on","about"],2,"verb_prep"),
  cc("c_048","She is allergic ___ cats, so she can't visit their house.","to",["from","with","of"],1,"adjective_prep"),
  cc("c_049","He gets on very well ___ his new colleagues.","with",["to","about","at"],2,"verb_prep"),
  cc("c_050","He was disappointed ___ the outcome of the vote.","with",["about","in","by"],3,"adjective_prep"),
]

F="famous_lines"
famous_cards = [
  c("f_001",F,"May the Force be ___ you.","with",["for","in","on"],"rule_with_accompaniment",1,True,False,"Star Wars (1977)"),
  c("f_002",F,"Welcome ___ the Hotel California.","to",["in","at","for"],"rule_to_destination",1,True,False,"Hotel California — Eagles (1977)"),
  c("f_003",F,"We're living ___ a prayer.","on",["in","for","by"],"rule_irregular_collocation",2,True,True,"Livin' on a Prayer — Bon Jovi (1986)"),
  c("f_004",F,"The answer is blowin' ___ the wind.","in",["on","with","through"],"rule_in_enclosed_space",1,True,False,"Blowin' in the Wind — Bob Dylan (1963)"),
  c("f_005",F,"The Sound ___ Silence.","of",["from","in","about"],"rule_of_possession",1,True,False,"The Sound of Silence — Simon & Garfunkel (1964)"),
  c("f_006",F,"Lean ___ me, when you're not strong.","on",["to","with","by"],"rule_irregular_collocation",2,True,True,"Lean on Me — Bill Withers (1972)"),
  c("f_007",F,"Stand ___ me. Don't be afraid.","by",["with","for","near"],"rule_irregular_collocation",2,True,True,"Stand by Me — Ben E. King (1961)"),
  c("f_008",F,"You've got a friend ___ me.","in",["with","for","from"],"rule_irregular_collocation",2,True,True,"You've Got a Friend in Me — Randy Newman / Toy Story (1995)"),
  c("f_009",F,"Don't you forget ___ me.","about",["of","from","with"],"rule_about_topic",1,True,False,"Don't You (Forget About Me) — Simple Minds (1985)"),
  c("f_010",F,"I'll be there ___ you.","for",["with","to","at"],"rule_for_purpose",1,True,False,"I'll Be There for You — The Rembrandts / Friends (1994)"),
  c("f_011",F,"Born ___ the USA.","in",["on","at","from"],"rule_in_area",1,True,False,"Born in the USA — Bruce Springsteen (1984)"),
  c("f_012",F,"Walking ___ sunshine.","on",["in","with","through"],"rule_irregular_collocation",2,True,True,"Walking on Sunshine — Katrina and the Waves (1985)"),
  c("f_013",F,"Take ___ me.","on",["to","in","with"],"rule_irregular_collocation",3,True,True,"Take On Me — A-ha (1985)"),
  c("f_014",F,"Riders ___ the storm.","on",["in","through","of"],"rule_on_surface",2,True,False,"Riders on the Storm — The Doors (1971)"),
  c("f_015",F,"Singin' ___ the rain.","in",["on","through","under"],"rule_in_area",1,True,False,"Singin' in the Rain — Gene Kelly (1952)"),
  c("f_016",F,"That's one small step ___ man.","for",["of","to","by"],"rule_for_purpose",1,True,False,"Neil Armstrong, Moon landing (1969)"),
  c("f_017",F,"Bridge ___ troubled water.","over",["on","through","above"],"rule_irregular_collocation",2,True,False,"Bridge over Troubled Water — Simon & Garfunkel (1970)"),
  c("f_018",F,"Get ___ the bus, Gus.","on",["in","off","to"],"rule_on_transport",1,True,False,"50 Ways to Leave Your Lover — Simon & Garfunkel (1975)"),
  c("f_019",F,"Reach ___ the sky!","for",["to","up","at"],"rule_for_purpose",1,True,False,"Toy Story — Woody (1995)"),
  c("f_020",F,"I'm ___ the top of the world, Ma.","on",["at","in","to"],"rule_on_surface",2,True,True,"Top of the World — The Carpenters (1972)"),
  c("f_021",F,"Knock ___ heaven's door.","on",["at","to","for"],"rule_on_surface",2,True,False,"Knockin' on Heaven's Door — Bob Dylan (1973)"),
  c("f_022",F,"Message ___ a bottle.","in",["on","from","inside"],"rule_in_enclosed_space",1,True,False,"Message in a Bottle — The Police (1979)"),
  c("f_023",F,"Dancing ___ the moonlight.","in",["on","under","by"],"rule_in_area",1,True,False,"Dancing in the Moonlight — King Harvest (1972)"),
  c("f_024",F,"In the name ___ love.","of",["from","for","about"],"rule_of_possession",1,True,False,"Pride (In the Name of Love) — U2 (1984)"),
  c("f_025",F,"Life is like a box ___ chocolates.","of",["with","from","full"],"rule_of_possession",1,True,False,"Forrest Gump (1994)"),
  c("f_026",F,"Fight ___ your right to party.","for",["on","with","about"],"rule_for_purpose",1,True,False,"(You Gotta) Fight for Your Right — Beastie Boys (1986)"),
  c("f_027",F,"Waiting ___ a girl like you.","for",["on","with","to"],"rule_for_purpose",1,True,False,"Waiting for a Girl Like You — Foreigner (1981)"),
  c("f_028",F,"Thinking ___ you.","of",["about","for","with"],"rule_about_topic",3,True,False,"Thinking of You — Katy Perry (2009) / various"),
  c("f_029",F,"On the road ___ nowhere.","to",["for","of","towards"],"rule_to_destination",1,True,False,"Road to Nowhere — Talking Heads (1985)"),
  c("f_030",F,"Somewhere ___ a rainbow.","over",["above","beyond","through"],"rule_irregular_collocation",1,True,False,"Somewhere Over the Rainbow — Wizard of Oz (1939)"),
]

CLUSTERS = [
  {
    "id": "place_in_on_at",
    "title": "IN / ON / AT — Place",
    "subtitle": "Where exactly are you?",
    "prepositions": ["in","on","at"],
    "intro_rules": ["rule_in_enclosed_space","rule_in_area","rule_on_surface","rule_on_transport","rule_at_specific_point","rule_at_event"],
    "contrast_note": "IN = inside an area or space. ON = touching a surface. AT = a precise point. Context decides.",
    "cards": place_cards,
  },
  {
    "id": "time_in_on_at",
    "title": "IN / ON / AT — Time",
    "subtitle": "When does it happen?",
    "prepositions": ["in","on","at"],
    "intro_rules": ["rule_in_long_period","rule_on_day","rule_at_time"],
    "contrast_note": "IN = long periods. ON = days and dates. AT = clock times and fixed moments.",
    "cards": time_cards,
  },
  {
    "id": "duration_by_until_for",
    "title": "BY / UNTIL / FOR — Time Spans",
    "subtitle": "How long, and when does it end?",
    "prepositions": ["by","until","for"],
    "intro_rules": ["rule_by_deadline","rule_until_continuous","rule_for_duration"],
    "contrast_note": "BY = deadline (finished no later than). UNTIL = continuous up to a point. FOR = total duration.",
    "cards": duration_cards,
  },
  {
    "id": "movement_to_for_with",
    "title": "TO / FOR / WITH",
    "subtitle": "Direction, purpose, and company",
    "prepositions": ["to","for","with"],
    "intro_rules": ["rule_to_destination","rule_for_purpose","rule_with_accompaniment"],
    "contrast_note": "TO = movement or direction. FOR = purpose or recipient. WITH = accompanying or using.",
    "cards": movement_cards,
  },
  {
    "id": "origin_of_about_from",
    "title": "FROM / OF / ABOUT",
    "subtitle": "Origins, content, and topics",
    "prepositions": ["from","of","about"],
    "intro_rules": ["rule_from_origin","rule_of_possession","rule_about_topic"],
    "contrast_note": "FROM = starting point or source. OF = part, content, or belonging. ABOUT = the topic or subject.",
    "cards": origin_cards,
  },
  {
    "id": "collocations",
    "title": "Fixed Phrases",
    "subtitle": "These don't follow rules — you just learn them.",
    "prepositions": ["in","on","at","to","for","with","of","about","from"],
    "intro_rules": ["rule_irregular_collocation"],
    "contrast_note": "These verb + preposition and adjective + preposition pairs are fixed. There is no spatial logic. Memorize them as units.",
    "cards": collocation_cards,
  },
  {
    "id": "famous_lines",
    "title": "You've Heard This Before",
    "subtitle": "Songs, films, and famous quotes",
    "prepositions": ["in","on","at","to","for","with","of","about","from","by","over"],
    "intro_rules": [],
    "contrast_note": "You probably know these — now identify the preposition.",
    "cards": famous_cards,
  },
]

data = {"version": "1.0", "rules": RULES, "clusters": CLUSTERS}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

total = sum(len(cl["cards"]) for cl in CLUSTERS)
print(f"Written {OUT}")
print(f"Clusters: {len(CLUSTERS)}, Cards: {total}")
for cl in CLUSTERS:
    print(f"  {cl['id']}: {len(cl['cards'])} cards")
